// Generated by https://quicktype.io

import { DataUser } from "./AuthInterface";
import { Content } from "./ProducstListInterface";
import { ActionsProductTypes } from "./types/ProductsType";

export interface FavList {
    code:    string;
    message: string;
    result:  ResultGeneric;
}

export interface ResultGeneric {
    content:          FavContent[];
    pageable:         Pageable;
    totalPages:       number;
    totalElements:    number;
    last:             boolean;
    numberOfElements: number;
    size:             number;
    first:            boolean;
    number:           number;
    sort:             Sort;
    empty:            boolean;
}

export interface FavContent {
    idFavorito:number;
    producto:Content
    usuario:DataUser
}

export interface Pageable {
    sort:       Sort;
    pageNumber: number;
    pageSize:   number;
    offset:     number;
    paged:      boolean;
    unpaged:    boolean;
}

export interface Sort {
    sorted:   boolean;
    unsorted: boolean;
    empty:    boolean;
}

export interface ProductsAction {
    type:ActionsProductTypes,
    payload:RequestPageableGenericFav
}

export interface RequestPageableGenericFav {
    isLoading:boolean,
    isError:boolean,
    isSuccess:boolean,
    data:ResultGeneric
}
