// Generated by https://quicktype.io

export interface ProductsList {
    code:    string;
    message: string;
    result:  ResultProduct;
}

export interface ResultProduct {
    content:          Content[];
    pageable:         Pageable;
    totalPages:       number;
    totalElements:    number;
    last:             boolean;
    numberOfElements: number;
    size:             number;
    first:            boolean;
    number:           number;
    sort:             Sort;
    empty:            boolean;
}

export interface Content {
    idItem:       number;
    nombre:       string;
    idCategoria:  number;
    precio:       number;
    precioOferta: number;
    imagen:      null;
}

export interface Pageable {
    sort:       Sort;
    pageNumber: number;
    pageSize:   number;
    offset:     number;
    paged:      boolean;
    unpaged:    boolean;
}

export interface Sort {
    sorted:   boolean;
    unsorted: boolean;
    empty:    boolean;
}
